version: "3"
services:
  hmpps-remand-and-sentencing-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-remand-and-sentencing-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
  remand-and-sentencing-db:
    image: postgres:15
    networks:
      - hmpps
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ras-pass
      - POSTGRES_USER=ras-user
      - POSTGRES_DB=ras
networks:
  hmpps:
