# helm_deploy/hmpps-remand-and-sentencing-api/templates/cronjob-document-table-cleanup.yaml
  {{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-document-table-cleanup
  labels:
    app.kubernetes.io/name: hmpps-remand-and-sentencing-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cronjob-cleanup
    app.kubernetes.io/job-name: document-table-cleanup-cronjob

spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: hmpps-remand-and-sentencing-api
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/component: cronjob-cleanup
            app.kubernetes.io/job-name: document-table-cleanup-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup-runner
              image: curlimages/curl:latest
              imagePullPolicy: IfNotPresent
              command: ["curl"]
              args:
                - "-X"
                - "POST"
                - "http://{{ .Release.Name }}-generic-service-service.{{ .Release.Namespace }}:{{ .Values.generic-service.port }}/internal/document-table-cleanup"
  {{- end }}