package uk.gov.justice.digital.hmpps.hmppsremandandsentencingapi.jpa.repository.batch

import org.springframework.data.repository.CrudRepository
import uk.gov.justice.digital.hmpps.hmppsremandandsentencingapi.jpa.entity.batch.ManyChargesToSentenceFixQueueEntity

interface MultipleChargesSingleSentenceFixQueueRepository : CrudRepository<ManyChargesToSentenceFixQueueEntity, Long>
