package uk.gov.justice.digital.hmpps.hmppsremandandsentencingapi.domain

enum class EventType(val order: Int) {
  COURT_CASE_INSERTED(0),
  COURT_CASE_UPDATED(10),
  COURT_CASE_DELETED(20),
  CHARGE_INSERTED(30),
  CHARGE_UPDATED(40),
  CHARGE_DELETED(50),
  COURT_APPEARANCE_INSERTED(60),
  COURT_APPEARANCE_UPDATED(70),
  COURT_APPEARANCE_DELETED(80),
  SENTENCE_INSERTED(90),
  SENTENCE_UPDATED(100),
  SENTENCE_DELETED(110),
  LEGACY_COURT_CASE_REFERENCES_UPDATED(120),
  RECALL_INSERTED(130),
  RECALL_UPDATED(140),
  RECALL_DELETED(150),
}
