COMMENT ON TABLE Charge IS E'Description: Holds each instance of a charge. A charge is the offence a person as committed and is being charged for.\nData Quality Issues: offence_date is a mandatory field in RaS and NOMIS but historically has not been in NOMIS so will be missing on some legacy cases.\n   Data Quality Parameter: Completeness\n   Source of Data Quality Issue: NOMIS \nNOMIS Equivalent Entity: offender_charges \nDomain: Person offences/convictions';
COMMENT ON TABLE Charge_Outcome IS E'Description: Holds metadata of the charge outcome.\nData Quality Issues: The outcome_name list contained within NOMIS is extensive leading to user error in selection, they are also not mutually exclusive. RaS has reduced this list down as it was overly extensive and led to user error in selections. Thus, in the bidirectional sync, this is not a 1-to-1 mapping between the lists in NOMIS and RaS.\n   Data Quality Parameter: Accuracy\n   Source of Data Quality Issue: NOMIS \nNOMIS Equivalent Entity: offence_result_codes \nDomain: Person offences/convictions';
COMMENT ON TABLE Appearance_Charge IS E'Description: Holds the charge related to each court appearance. \nNOMIS Equivalent Entity: court_event_charges \nDomain: Person offences/convictions';
COMMENT ON TABLE Court_Case IS E'Description: Holds each instance of a court case. \nNOMIS Equivalent Entity: offender_cases \nDomain: Person Court Schedules';
COMMENT ON TABLE Court_Appearance IS E'Description: Holds each instance of a court appearance. \nNOMIS Equivalent Entity: court_events, offender_cases, offender_case_identifiers \nDomain: Person Court Schedules';
COMMENT ON TABLE Next_Court_Appearance IS E'Description: Holds details of the next planned court appearance. This is a supplementary entity in the data model. \nNOMIS Equivalent Entity: court_events \nDomain: Person Court Schedules';
COMMENT ON TABLE Appearance_Outcome IS E'Description: Holds metadata of the outcome from a court appearance. \nNOMIS Equivalent Entity: offence_result_codes \nDomain: Person offences/convictions';
COMMENT ON TABLE Period_Length IS E'Description: Holds details of the duration of a sentence. This is a suplementary entity in the data model. \nNOMIS Equivalent Entity: offender_sentence_terms \nDomain: Court results including person sentences';
COMMENT ON TABLE Sentence IS E'Description: Holds each instance of a sentence. \nNOMIS Equivalent Entity: offender_sentences \nDomain: Court results including person sentences';
COMMENT ON TABLE Sentence_Type IS E'Description: Holds meta data that defines the properties of different sentence types. \nNOMIS Equivalent Entity: sentence_calc_types \nDomain: Court results including person sentences';
COMMENT ON TABLE Recall IS E'Description: Holds recall information at a parent level, where multiple sentences may be affected by a recall. A recall is where an offender is out on licence and their licence is then revoked, requiring them to return to prison.\nData Quality Issues: NOMIS only stores the most recent recall for an offender, the history of an offenders sentences prior to the latest recall cannot be seen. In RaS, all recalls and recall history are stored. It is not possible to look back retrospectively at recalls that have been made in the past through NOMIS. If a recall has been synced from NOMIS, then revocation will not be populated as this information is not recorded in NOMIS.\n   Data Quality Parameter: Accuracy\n   Source of Data Quality Issue: NOMIS \nNOMIS Equivalent Entity: offender_sentences \nDomain: Person Recalls';
COMMENT ON TABLE Recall_Sentence IS E'Description: Holds recall information at a child level, where the recall information affects a specific sentence. \nNOMIS Equivalent Entity: offender_sentences \nDomain: Court results including person sentences';
COMMENT ON TABLE Recall_Type IS E'Description: Holds information about the different types of recall that can be chosen by the probation service depending on the sentences being recalled. \nNOMIS Equivalent Entity: sentence_calc_types \nDomain: Person Recalls';
COMMENT ON COLUMN Charge.charge_uuid IS E'Description: The id related to the charge. The charge may get amended so the charge uuid can change over time. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.offence_code IS E'Description: A code to represent an offence where the offence is used in the generic sense covering the reasons for bringing a court case against a defendant. \nSource System: Manage Offences System';
COMMENT ON COLUMN Charge.offence_start_date IS E'Description: The date of when the offence started. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.offence_end_date IS E'Description: The date of when the offence ended. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.status_id IS E'Description: The id of the status of the charge. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.charge_outcome_id IS E'Description: The id of the outcome of the charge. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.superseding_charge_id IS E'Description: The id related to the charge record which is replacing a historic charge record. This is used for auditing purposes. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.terror_related IS E'Description: A flag to determine whether the charge is terror related or not. This impacts release date calculation. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.created_At IS E'Description: Auto created timestamp of when the charge record was created. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge.legacy_data IS E'Description: Legacy JSON to hold details for charges that are not supported within RaS. This is used for the bidirectional sync between NOMIS and DPS. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge_Outcome.outcome_name IS E'Description: The name of the charge outcome. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge_Outcome.outcome_uuid IS E'Description: The id of the charge outcome. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge_Outcome.nomis_code IS E'Description: The equivalent NOMIS code for charge outcome_name for the purpose of mapping during bidirectional sync between NOMIS and DPS .  \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge_Outcome.outcome_type IS E'Description: The type of the outcome charge. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge_Outcome.display_order IS E'Description: The order for the charge outcomes to be displayed on the UI. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Charge_Outcome.disposition_code IS E'Description: The dispositian code is used to determine how remand periods are counted. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Charge.appearance_id IS E'Description: The id related to the appearance. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Charge.charge_id IS E'Description: The id related to the charge. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.appearance_uuid IS E'Description: The unique id related to the court appearance. The appearance may get amended so the appearance uuid can change over time. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.appearance_outcome_id IS E'Description: The id related to the outcome of the court appearance. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.court_case_id IS E'Description: The id related to the court case. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.court_code IS E'Description: The code of the court where the appearance is taking place. These codes are held in Court Register. \nSource System: Court Register';
COMMENT ON COLUMN Court_Appearance.court_case_reference IS E'Description: The refrerence number  assigned to  the court case. \nSource System: Common Platform, Libra, Xhibit';
COMMENT ON COLUMN Court_Appearance.appearance_date IS E'Description: The date of the court appearance. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.status_id IS E'Description: The id of the status of the court appearance. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.next_court_appearance_id IS E'Description: The id related to the next court appearance. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.created_at IS E'Description: The timestamp of when the court appearance record was created. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.created_prison IS E'Description: The prison where the record was initially created, this is used when offenders are transferred around to different prisons. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.warrant_type IS E'Description: The type of the warrant for the court case appearance. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.overall_conviction_date IS E'Description:  The date an offender was declared guilty of a charge offence. Used when there are multiple sentences related to a court appearance. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Appearance.legacy_data IS E'Description: Legacy JSON to hold details for court appearance details that are not supported within RaS. This is used for the bidirectional sync between NOMIS and DPS. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Case.prisoner_id IS E'Description: The id of the prisoner related to  the court_case. \nSource System: NOMIS';
COMMENT ON COLUMN Court_Case.case_unique_identifier IS E'Description: The id related to the court case. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Case.latest_court_appearance_id IS E'Description: The id related to the latest court appearance in the court case. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Case.created_at IS E'Description: The timestamp of when the court case record was created. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Case.status_id IS E'Description: The id of the status of the court case. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Court_Case.legacy_data IS E'Description: Legacy sentence type JSON to hold the court case details that are not supported within RaS. This is used for the bidirectional sync between NOMIS and DPS. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Next_Court_Appearance.appearance_date IS E'Description: The date of the next court appearance for the court case. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Next_Court_Appearance.court_code IS E'Description: The code of the court where the next appearance will take place. These codes are held in Court Register \nSource System: Court Register';
COMMENT ON COLUMN Next_Court_Appearance.appearance_type_id IS E'Description: The id for the type of the appearance of the next court appearance. The type can be a court appearance or video link. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Next_Court_Appearance.appearance_time IS E'Description: The time of the next court appearance. Optional \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Next_Court_Appearance.future_skeleton_appearance_id IS E'Description: The id of the next future court appearance, no outcome or warrant type will be populated yet. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Outcome.outcome_name IS E'Description: The name of the outcome at the court appearance level.  \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Outcome.outcome_uuid IS E'Description: The unique id of the appearance outcome. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Outcome.nomis_code IS E'Description: The equivalent NOMIS code for appearance outcome for the purpose of mapping during bidirectional sync between NOMIS and DPS .  \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Outcome.outcome_type IS E'Description: The type of the appearance outcome. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Outcome.display_order IS E'Description: The order for the appearance outcomes to be displayed on the UI. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Outcome.related_charge_outcome_uuid IS E'Description: The unique id of the related charge that the appearance outcome refers to. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Appearance_Outcome.is_sub_list IS E'Description: If the outcome type is neither remand or sentencing then other options are shown as a list on the UI if the value is TRUE. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.years IS E'Description: The number of years of the sentence. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.months IS E'Description: The number of months of the sentence. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.weeks IS E'Description: The number of weeks of the sentence. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.days IS E'Description: The number of days of the sentence. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.period_order IS E'Description: The order of the units that make up a period, eg years, months, weeks, days. Note that the length of a term 1 month and 1 year, for example, may be different to a term of 1 year and 1 month. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.period_length_type IS E'Description: The nature of the period entered. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.sentence_id IS E'Description: The id of the sentence which the period length is related to. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.appearance_id IS E'Description: The id of the specific court appearance the period length relates to, in order to record an overall sentence period. Also, used to validate the period of it’s constituent sentences. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Period_Length.legacy_data IS E'Description: Legacy JSON to hold details for sentences period length types that are not supported within RaS. This is used for the bidirectional sync between NOMIS and DPS. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.sentence_uuid IS E'Description: The id of the sentence. The sentence may get amended so the sentence uuid can change over time. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.status_id IS E'Description: The id of the status of the sentence. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.created_at IS E'Description: The timestamp of when the sentence record was created. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.created_prison IS E'Description: The prison where the record was initially created, this is used when offenders are transferred around to different prisons. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.superseding_sentence_id IS E'Description: The id related to the sentence record which is replacing a historic sentence record. This is used for auditing purposes. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.charge_id IS E'Description: The id of the specific instance of a charge for which the offender has been sentenced. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.sentence_serve_type IS E'Description: The relationship of the sentence with other sentences. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.consecutive_to_id IS E'Description: The sentence that follows the sentence in a consecutive sentence envelope. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.conviction_date IS E'Description:  The date an offender was declared guilty of a charge offence.  \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.sentence_type_id IS E'Description: The id of the sentence type. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence.legacy_data IS E'Description: Legacy JSON to hold details for sentences that are not supported within RaS. This is used for the bidirectional sync between NOMIS and DPS. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.sentence_type_uuid IS E'Description: The id of the sentence type. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.description IS E'Description: The text description of the sentence type. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.min_age_inclusive IS E'Description: This field is used by the RaS UI to determine the sentence types that are applicable based on the age of an offender. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.max_age_exclusive IS E'Description: This field is used by the RaS UI to determine the sentence types that are applicable based on the age of an offender. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.min_date_inclusive IS E'Description: This field is used by the RaS UI to determine the sentence types that are applicable based on the conviction date. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.max_date_exclusive IS E'Description: This field is used by the RaS UI to determine the sentence types that are applicable based on the conviction date. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.classification IS E'Description: Defines the class of sentence in order to inform the behaviour to the RaS UI. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.nomis_cja_code IS E'Description: The equivalent NOMIS CJA code. CJA code  refers to the Act/Code that the sentence type is active under. Four Sentencing Acts/Codes exist – 1967, 1991, 2003, and 2020.  \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.nomis_sentence_calc_type IS E'Description: The equivalent NOMS calculation type for the given sentence. This will be used in the bidirectional sync between NOMIS and RaS. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.hint_text IS E'Description: Provides further context. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Sentence_Type.display_order IS E'Description: The order for the sentence types to be displayed on the UI. \nSource System: Remand & Sentencing';
COMMENT ON COLUMN Recall.id IS E'Description: The unique id for the overarching recall. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall.recall_uuid IS E'Description: The unique id of the overarching recall which is displayed on the UI. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall.prisoner_id IS E'Description: The id of the prisoner that is being recalled. \nSource System: NOMIS';
COMMENT ON COLUMN Recall.revocation_date IS E'Description: The date when the probation service approved the recall for the prisoner. \nSource System: Consider a Recall';
COMMENT ON COLUMN Recall.return_to_custody_date IS E'Description: The date the prisoner was arrested. If the prisoner was already in custody at the time of the recall then this will be the same as the revocation_date. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall.recall_type_id IS E'Description: Which kind of recall was selected by the probation service, this can be restricted based on the kinds of sentences being recalled. \nSource System: Consider a Recall';
COMMENT ON COLUMN Recall.created_at IS E'Description: The timestamp of when the overarching recall was created. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall.created_by_username IS E'Description: The username that initially created the overarching recall. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Sentence.id IS E'Description: The unique id of the specific recall sentence. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Sentence.recall_sentence_uuid IS E'Description: The unique id of the specific recall sentence which is displayed on the UI. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Sentence.recall_id IS E'Description: The overarching recall that this specific sentence is being recalled under. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Sentence.sentence_id IS E'Description: The id of the specific sentence that is being recalled. Individual sentences can be recalled multiple times. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Sentence.legacy_data IS E'Description: Legacy JSON to hold details for recall sentences. This is used for the bidirectional sync between NOMIS and DPS. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Sentence.created_at IS E'Description: The timestamp of when the recall sentence was created. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Sentence.created_by_username IS E'Description: The username that initially created the recall sentence. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Type.id IS E'Description: The id of the recall type. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Type.code IS E'Description: The short code used to reference what kind of recall was decided upon by the probation service and entered onto the revocation order. \nSource System: Record a Recall';
COMMENT ON COLUMN Recall_Type.description IS E'Description: The text description of the recall type. \nSource System: Record a Recall';
