CREATE TABLE court_appearance_history (
	id SERIAL PRIMARY KEY,
	appearance_uuid uuid NOT NULL,
	appearance_outcome_id int NULL,
	court_case_id int NOT NULL,
	court_code varchar NOT NULL,
	court_case_reference varchar NULL,
	appearance_date date NOT NULL,
	status_id smallint NOT NULL,
	next_court_appearance_id int NULL,
	previous_appearance_id int NULL,
	warrant_id varchar NULL,
	created_at timestamp with time zone NOT NULL,
	created_by varchar NOT NULL,
	created_prison varchar NULL,
	updated_at timestamp with time zone NULL,
    updated_by varchar NULL,
    updated_prison varchar NULL,
	warrant_type varchar DEFAULT 'REMAND'::character varying NOT NULL,
	tagged_bail int NULL,
	overall_conviction_date date NULL,
	legacy_data jsonb NULL,
	original_appearance_id int references court_appearance(id)
);